/* tslint:disable */
/* eslint-disable */
/**
 * Accommodation Service - Accommodation Owner APIs
 * Api Documentation for Accommodation Owner Users
 *
 * The version of the OpenAPI document: Accommodation Owner
 * Contact: amir.hossein.khalouei@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentResponseDto
 */
export interface CommentResponseDto {
    /**
     * 
     * @type {string}
     * @memberof CommentResponseDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommentResponseDto
     */
    date?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommentResponseDto
     */
    rate?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CommentResponseDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommentResponseDto
     */
    source?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommentResponseDto
     */
    sourceId?: number | null;
}


