/* tslint:disable */
/* eslint-disable */
/**
 * Accommodation Service - Accommodation Owner APIs
 * Api Documentation for Accommodation Owner Users
 *
 * The version of the OpenAPI document: Accommodation Owner
 * Contact: amir.hossein.khalouei@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommentReportResponseDto } from './comment-report-response-dto';

/**
 * 
 * @export
 * @interface CommentReportResponseDtoResponsePackage
 */
export interface CommentReportResponseDtoResponsePackage {
    /**
     * 
     * @type {string}
     * @memberof CommentReportResponseDtoResponsePackage
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {CommentReportResponseDto}
     * @memberof CommentReportResponseDtoResponsePackage
     */
    result?: CommentReportResponseDto;
    /**
     * 
     * @type {boolean}
     * @memberof CommentReportResponseDtoResponsePackage
     */
    success?: boolean;
}


