/* tslint:disable */
/* eslint-disable */
/**
 * Accommodation Service - Accommodation Owner APIs
 * Api Documentation for Accommodation Owner Users
 *
 * The version of the OpenAPI document: Accommodation Owner
 * Contact: amir.hossein.khalouei@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentSourceDetailsDto
 */
export interface CommentSourceDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof CommentSourceDetailsDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CommentSourceDetailsDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommentSourceDetailsDto
     */
    site?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommentSourceDetailsDto
     */
    slug?: string | null;
}


