/* tslint:disable */
/* eslint-disable */
/**
 * Accommodation Service - Accommodation Owner APIs
 * Api Documentation for Accommodation Owner Users
 *
 * The version of the OpenAPI document: Accommodation Owner
 * Contact: amir.hossein.khalouei@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetCommentsRequestDto
 */
export interface GetCommentsRequestDto {
    /**
     * 
     * @type {string}
     * @memberof GetCommentsRequestDto
     */
    startDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCommentsRequestDto
     */
    endDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCommentsRequestDto
     */
    score?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetCommentsRequestDto
     */
    source?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetCommentsRequestDto
     */
    sortBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCommentsRequestDto
     */
    sortDirection?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCommentsRequestDto
     */
    text?: string | null;
}


