/* tslint:disable */
/* eslint-disable */
/**
 * Accommodation Service - Accommodation Owner APIs
 * Api Documentation for Accommodation Owner Users
 *
 * The version of the OpenAPI document: Accommodation Owner
 * Contact: amir.hossein.khalouei@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MetaCommentReportResponseDto
 */
export interface MetaCommentReportResponseDto {
    /**
     * 
     * @type {number}
     * @memberof MetaCommentReportResponseDto
     */
    totalCityComments?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaCommentReportResponseDto
     */
    foundComments?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaCommentReportResponseDto
     */
    positiveCommentsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaCommentReportResponseDto
     */
    negativeCommentsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaCommentReportResponseDto
     */
    neutralCommentsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaCommentReportResponseDto
     */
    averageRate?: number;
}


