/* tslint:disable */
/* eslint-disable */
/**
 * Accommodation Service - Accommodation Owner APIs
 * Api Documentation for Accommodation Owner Users
 *
 * The version of the OpenAPI document: Accommodation Owner
 * Contact: amir.hossein.khalouei@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OwnerCommentResponseDto
 */
export interface OwnerCommentResponseDto {
    /**
     * 
     * @type {string}
     * @memberof OwnerCommentResponseDto
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof OwnerCommentResponseDto
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof OwnerCommentResponseDto
     */
    averageRate?: number;
}


