/* tslint:disable */
/* eslint-disable */
/**
 * Accommodation Service - Accommodation Owner APIs
 * Api Documentation for Accommodation Owner Users
 *
 * The version of the OpenAPI document: Accommodation Owner
 * Contact: amir.hossein.khalouei@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StringIEnumerableResponsePackage
 */
export interface StringIEnumerableResponsePackage {
    /**
     * 
     * @type {string}
     * @memberof StringIEnumerableResponsePackage
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof StringIEnumerableResponsePackage
     */
    result?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof StringIEnumerableResponsePackage
     */
    success?: boolean;
}


