/* tslint:disable */
/* eslint-disable */
/**
 * User
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: User
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ExternalLoginRequestDto } from '../model';
// @ts-ignore
import { LoginResponseDto } from '../model';
/**
 * ExternalLoginApi - axios parameter creator
 * @export
 */
export const ExternalLoginApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ExternalLoginRequestDto} [externalLoginRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiExternalLoginGooglePost: async (externalLoginRequestDto?: ExternalLoginRequestDto, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ExternalLogin/google`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(externalLoginRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExternalLoginApi - functional programming interface
 * @export
 */
export const ExternalLoginApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExternalLoginApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ExternalLoginRequestDto} [externalLoginRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiExternalLoginGooglePost(externalLoginRequestDto?: ExternalLoginRequestDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiExternalLoginGooglePost(externalLoginRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ExternalLoginApi - factory interface
 * @export
 */
export const ExternalLoginApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExternalLoginApiFp(configuration)
    return {
        /**
         * 
         * @param {ExternalLoginRequestDto} [externalLoginRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiExternalLoginGooglePost(externalLoginRequestDto?: ExternalLoginRequestDto, options?: any): AxiosPromise<LoginResponseDto> {
            return localVarFp.apiExternalLoginGooglePost(externalLoginRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiExternalLoginGooglePost operation in ExternalLoginApi.
 * @export
 * @interface ExternalLoginApiApiExternalLoginGooglePostRequest
 */
export interface ExternalLoginApiApiExternalLoginGooglePostRequest {
    /**
     * 
     * @type {ExternalLoginRequestDto}
     * @memberof ExternalLoginApiApiExternalLoginGooglePost
     */
    readonly externalLoginRequestDto?: ExternalLoginRequestDto
}

/**
 * ExternalLoginApi - object-oriented interface
 * @export
 * @class ExternalLoginApi
 * @extends {BaseAPI}
 */
export class ExternalLoginApi extends BaseAPI {
    /**
     * 
     * @param {ExternalLoginApiApiExternalLoginGooglePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExternalLoginApi
     */
    public apiExternalLoginGooglePost(requestParameters: ExternalLoginApiApiExternalLoginGooglePostRequest = {}, options?: any) {
        return ExternalLoginApiFp(this.configuration).apiExternalLoginGooglePost(requestParameters.externalLoginRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}
