/* tslint:disable */
/* eslint-disable */
/**
 * User
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: User
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HotelSearchHistoryRequest
 */
export interface HotelSearchHistoryRequest {
    /**
     * 
     * @type {string}
     * @memberof HotelSearchHistoryRequest
     */
    cityTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HotelSearchHistoryRequest
     */
    hotelTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HotelSearchHistoryRequest
     */
    checkInDate?: string;
    /**
     * 
     * @type {string}
     * @memberof HotelSearchHistoryRequest
     */
    checkOutDate?: string;
    /**
     * 
     * @type {number}
     * @memberof HotelSearchHistoryRequest
     */
    passengerCount?: number | null;
}


