/* tslint:disable */
/* eslint-disable */
/**
 * User
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: User
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginRequestDto
 */
export interface LoginRequestDto {
    /**
     * 
     * @type {string}
     * @memberof LoginRequestDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginRequestDto
     */
    password?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LoginRequestDto
     */
    rememberMe?: boolean;
}


