/* tslint:disable */
/* eslint-disable */
/**
 * User
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: User
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignUpHotelRequestDto
 */
export interface SignUpHotelRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SignUpHotelRequestDto
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpHotelRequestDto
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpHotelRequestDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpHotelRequestDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpHotelRequestDto
     */
    phoneNumber?: string | null;
}


