/* tslint:disable */
/* eslint-disable */
/**
 * User
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: User
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignUpRequestDto
 */
export interface SignUpRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SignUpRequestDto
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpRequestDto
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpRequestDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpRequestDto
     */
    phoneNumber?: string | null;
}


