/* tslint:disable */
/* eslint-disable */
/**
 * User
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: User
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserFullDetails
 */
export interface UserFullDetails {
    /**
     * 
     * @type {number}
     * @memberof UserFullDetails
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserFullDetails
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserFullDetails
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserFullDetails
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserFullDetails
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserFullDetails
     */
    email?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserFullDetails
     */
    completedInformation?: boolean;
}


